version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:latest
  environment:
    ## this enables colors in the output
    TERM: xterm

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.versionCache }}-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install Yarn Packages
          command: yarn install
      - save_cache:
          key: v{{ .Environment.versionCache }}-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - ~/.cache
      - run:
          name: Gatsby Build
          command: yarn build
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - app


  deploy:
    <<: *defaults

    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Firebase Deploy
          command: yarn deploy

workflows:
  version: 2
  test-build:
    jobs:
    - build
    - deploy:
        requires:
          - build
        filters:
          branches:
            only: master