version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.versionCache }}-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install Yarn Packages
          command: yarn install

      - save_cache:
          key: v{{ .Environment.versionCache }}-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - ./node_modules

      - run:
          name: Gatsby Build
          command: yarn build

      - run:
          name: Firebase Deploy
          command: yarn deploy

workflows:
  version: 2
  test-build:
    jobs:
    - build