---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections: 
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:latest
  mount_path: "/src"
  working_dir: "/src"
  instant_preview_command: npm run develop
